name: jccweb
recipe: drupal8
config:
  webroot: web
  php: '7.3'
proxy:
  pma:
    - pma.jccweb.lndo.site
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    xdebug: true
