module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  allowed_formats: 0
  automated_cron: 0
  backup_migrate: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_field: 0
  book: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_codemirror: 0
  ckeditor_templates: 0
  ckeditor_templates_ui: 0
  coffee: 0
  color: 0
  comment: 0
  config: 0
  config_delete: 0
  config_translation: 0
  contact: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  diff: 0
  dropdown_language: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference_revisions: 0
  facets: 0
  facets_summary: 0
  feeds: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  filter: 0
  fontawesome: 0
  fullcalendar_view: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  geofield_map: 0
  graphql: 0
  graphql_core: 0
  graphql_search_api: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  imagemagick: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jcc_book_navigation: 0
  jcc_judges_in_the_classroom: 0
  jcc_misc: 0
  kint: 0
  language: 0
  link: 0
  locale: 0
  mailsystem: 0
  media: 0
  media_library: 0
  menu_item_extras: 0
  menu_token: 0
  menu_ui: 0
  metatag: 0
  node: 0
  office_hours: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  search_api: 0
  search_api_db: 0
  sendgrid_integration: 0
  settings_tray: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  telephone: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  twig_vardumper: 0
  update: 0
  user: 0
  views_field_view: 0
  views_tree: 0
  views_ui: 0
  webform: 0
  webform_embed: 0
  webform_ui: 0
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  uswds_base: 0
  uswds_base_jcc: 0
  claro: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
