schemas: {  }
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://trialcourt-slo-light.png'
favicon:
  use_default: true
cdn_provider: ''
cdn_custom_img: 'https://cdn.jsdelivr.net/npm/uswds@2.0.2/dist/img'
cdn_custom_css: 'https://cdn.jsdelivr.net/npm/uswds@2.0.2/dist/css/uswds.css'
cdn_custom_css_min: 'https://cdn.jsdelivr.net/npm/uswds@2.0.2/dist/css/uswds.min.css'
cdn_custom_js: 'https://cdn.jsdelivr.net/npm/uswds@2.0.2/dist/js/uswds.js'
cdn_custom_js_min: 'https://cdn.jsdelivr.net/npm/uswds@2.0.2/dist/js/uswds.min.js'
uswds_header_style: extended
uswds_header_mega: 1
uswds_header_mega_display_second: 1
uswds_government_banner: 0
uswds_footer_style: big
uswds_footer_agency: 1
uswds_footer_agency_name: 'County of San Luis Obispo'
uswds_footer_agency_url: ''
uswds_footer_agency_logo: logo-dark.png
uswds_contact_center: ''
uswds_email: ''
uswds_phone: ''
uswds_facebook: '#facebook'
uswds_twitter: '#slo'
uswds_youtube: '#youtube'
uswds_rss: /rss.xml
uswds_paragraphs_edge_to_edge: 1
uswds_menu_accordion_duplicate_parent: 0
uswds_menu_bypass:
  primary_menu: 0
  secondary_menu: 0
  sidebar_first: 0
  sidebar_second: 0
  footer_menu: 0
_core:
  default_config_hash: 5lIIcBUmtGwZbqdvQjeqwxM8Rkmyt7UpxqQk9fHXRIU
uswds_header_hide_title: 1
uswds_header_hide_site_name: 1
uswds_header_hide_universal_nav: 0
