ignored_config_entities:
  - sendgrid_integration.settings
  - 'webform.webform.*'
  - uswds_base_jcc.settings
  - 'openid_connect.settings.*'
  - 'geocoder.geocoder_provider.*'
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
